title: Kartik Patel Portfolio
description: >-
  This is my Jekyll site hosted on GitHub Pages.
baseurl: ""   # leave empty for a user site (demoralizerr.github.io)
url: "https://demoralizerr.github.io"
theme: jekyll-theme-cayman
